# -*- coding: utf-8 -*-
"""HW01_591.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qIIRfxrsBL9KQpEimK0ux4t8N7hzAFZh

กำหนดให้ 

จำนวนวงเงินประกัน = y

รายได้ = x
"""

import math
import statistics

def find_square(l,square):
  #print("list=",l)
  #print("square list=",square)
  for index in l:
    #print("i=",index)
    item = pow(index,2)
    #print("item=",item)
    square.append(item)
    #print("square",square)
  return square

def find_multixy(x,y):
  result = []
  for index in range (len(x)):
    result.append(x[index]*y[index])
  return result

x = [7,8,10,8,13,12,6,12,18,9,15]
x_square = []
x_mean = statistics.mean(x)
x_sum = sum(x)
x_all_square_sum= (x_sum)**2

y = [9,20,22,15,27,30,18,25,36,17,30]
y_square = []
y_mean = statistics.mean(y)
y_sum = sum(y)
y_all_square_sum= (y_sum)**2

xy = sum(find_multixy(x,y))

x_square = find_square(x,x_square)
y_square = find_square(y,y_square)

x_each_square_sum = sum(x_square)
y_each_square_sum = sum(y_square)

print("x^2 = ",x_square)
print("y^2 = ",y_square)
print("mean x = ",x_mean)
print("mean y = ",y_mean)
print("sum x = ",x_sum)
print("sum y = ",y_sum)
print("sum (x^2) = ",x_each_square_sum)#sum each x^2
print("sum (y^2) = ",y_each_square_sum)
print("(sum x)^2 = ",x_all_square_sum)#sum x^2
print("(sum y)^2 = ",y_all_square_sum)
print("sum x(i)*y(i) = ", xy)#ผลรวมx*y

"""a = (y_mean)-b(x_mean)

b = [(sum(xy)) - ((sum(x)sum(y))/7)]/[sum(x^2)-(sum(x)^2)/7]
"""

#find a and b
b = (xy-(x_sum*y_sum/7))/(x_each_square_sum-(x_all_square_sum/7))
a = y_mean - b*x_mean

print("A = ",a)
print("B = ", b)

"""ได้สมการถดถอยคือ Y^ = -0.38669429503570996 - 2.146217264791465(X)"""

#ถ้ามีรายได้ 45,000บาท/เดือน ลูกค้าควรทำเงินประกันชีวิตเท่าไหร่
y_hat = a - (b*45000)
print("ลูกค้าควรทำเงินประกันวงเงิน "+ str(y_hat) + " บาท")

"""scatter plot"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array(x)
y = np.array(y)
plt.scatter(x,y, color = 'hotpink')
plt.show()