# -*- coding: utf-8 -*-
"""HW02_03_591.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_SwMhiTf0c00TEDNU8TL9GfjOm8V9_3b
"""

#(HW02_03_6xxxxxxxx) จากดโปรแกรมการสร้างตัวเลขสุ่มที่มีการกระจายแบบ normal จงทำการปรับโปรแกรมให้ทำการสุ่งตัวเลขทั้งหมดจำนวน 50 ตัว พร้อมทำการวาด Histogram ของ random variables ที่ได้

import math
import matplotlib.pyplot as plt
import numpy as np
import random as rd

x = []
y = []

def normal():
  u1 = rd.random()
  u2 = rd.random()
  z1 = math.sqrt(-2*math.log(u1))*math.cos(2*math.pi*u2)
  z2 = math.sqrt(-2*math.log(u1))*math.sin(2*math.pi*u2)
  return z1, z2

for i in range(10):
  z = normal()
  x.append(z[0])
  y.append(z[1])

plt.hist(x)
plt.show()

plt.hist(y)
plt.show()
