# -*- coding: utf-8 -*-
"""HW2_2_591.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y8auJ9-2vP9U9mJH057wWJer_Zt15W1M

จากโปรแกรมการสร้างตัวเลขสุ่มที่มีการกระจายแบบ poison จงทำการปรับโปรแกรมให้ทำการสุ่มตัวเลขทั้งหมดจำนวน 50 ตัว โดยกำหนดค่าเฉลี่ย = 2 พร้อมทำการวาด Histogram ของ Random ที่ได้
P(X=x)=[e^(-λ)*λ^(x)]/[x!];x=0,1,2,...
e=2.71828
"""

import math
import matplotlib.pyplot as plt
import numpy as np

lamb = 2
random_list = []
e = 2.71828

math.factorial(4)

def find_random_num(x):
  number = ((pow(e,-(lamb)))*(pow(lamb,x)))/(math.factorial(x))
  #round(number,10)
  return (number)

for i in range(50):
  print('i=',i)
  random_number = find_random_num(i)
  print("number=",random_number)
  random_list.append(random_number)
  print("list = ",random_list)

len(random_list)

plt.hist(random_list)
plt.show()